title: false
subtitle: Make PHP great again
author:
  - Oliver Fabel
institute:
  - FHNW
date: 01.11.2023
theme: default
innertheme: circles
outertheme: default
colortheme: wolverine
fonttheme: professionalfonts
section-titles: false
block-headings: true
toc-title: Table of Contents
colorlinks: true
linkcolor: black
urlcolor: blue
aspectratio: 169
titlegraphic: ./media/logo.eps.pdf
lang: en
version: 1.0.0
themeoptions: [ ]
header-includes:
  - \title{PHP}
  - \setbeamercolor{item projected}{bg=yellow!85!orange,fg=black}
  - \setbeamercolor{subitem projected}{bg=yellow!85!orange,fg=black}
  - \setbeamercolor{subsubitem projected}{bg=yellow!85!orange,fg=black}
  - \setbeamercolor{itemize item}{fg=yellow!85!orange}
  - \setbeamercolor{itemize subitem}{fg=yellow!85!orange}
  - \setbeamercolor{itemize subsubitem}{fg=yellow!85!orange}
  - \setbeamercolor{description item}{fg=black}
  - \setbeamersize{description width=0.25\textwidth}
  - \setbeamerfont{description item}{series=\bfseries}
  - \usepackage{etoolbox}
  - \usepackage{xpatch}
  - \makeatletter
  - |
    \patchcmd\beamer@@tmpl@frametitle{\insertframetitle}{%
      \ifdefempty{\insertsection}{%
        \insertframetitle
      }{%
        \insertsection:~\insertframetitle 
      }
    }{}{}
  - \makeatother
  - |
    \AtBeginSection[]{
      \begin{frame}[plain,c]
        \vskip0pt plus 1filll
        \begin{beamercolorbox}[sep=10pt,center]{title}
          \usebeamerfont{title}\insertsectionhead\par%
        \end{beamercolorbox}
        \vskip0pt plus 1filll
      \end{frame}
    }
  - |
    \setbeamertemplate{footline}{%
      \makebox[0.4\textwidth]{}
      \makebox[0.2\textwidth][c]{%
        \raisebox{5pt}{%
          \normalsize{\insertpagenumber}
        }
      }
      \makebox[0.4\textwidth][r]{%
        \includegraphics[height=0.6cm]{./media/logo.eps.pdf}\hspace{3pt}
      }
      \vspace{3pt}
    }

