timeline
    section Stone Age
    1993 : 0.*
         : Personal Home Page
         : Form Interpreter
    1995 : 1.*
    1997 : 2.*
    section Middle Age
    1998 : 3.*
         : New Parser
         : PHP: Hypertext Preprocessor
    2000 : 4.*
         : Zend Engine
    2004 : 5.*
         : Object Oriented Programming
         : Type declarations for object types
    section Modern PHP
    2015 : 7.*
         : Error Handling
         : Type declarations for scalar types
         : Return type declarations
         : New Operators
         : Performance
    2020 : 8.*
         : JIT compilation
         : Match expressions
         : Native annotations (called attributes)
         : New Operators
